### ISSUE TITLE
Support for UR3e or any other models other than UR10 ?

### ISSUE THREAD

**Issue by SharxRobotics** [UniversalRobots/Universal_Robots_Isaac_Driver#5]
The Readme file in this respository and in Isaac 2021 both mention support only for the UR10 model. Specifically, the Readme in this repository states:

> Isaac SDK uses kinematic trees to represent robot arms inside Isaac application. Currently there is only a kinematic tree representation of a UR10 robot. It can be found in Isaac SDK folder in "apps/assets/kinematic_trees/ur_10.kinematic.json".

We are testing a Universal Robots arm integrated on to a prototype of the Sharx Robotics version of the Nvidia Carter robotics mobile platform reference design.

[www.sharxrobotics.com](url)

The UR10 would be far too large for a mobile robot, so we're interested in support for the **UR3e** and possibly **UR5e**. There are apparently at least 4 files in Isaac that have data specific to a robot model: a JSON file for the kinematic tree, a URDF and 2 YAML files.

3 questions:

1. Until the files for the smaller robot arms become available, would it be safe to power up a UR3e arm and control it with this UR/Nvidia Isaac driver as is ?
2. Is anyone at UR or Nvidia working on the support files for the smaller e-series UR models ? If so, is there an ETA ?
3. What was the data source for the UR10 files: Public data from the brochures and manuals, proprietary data from inside UR source code, or experimentally derived data ?

By the way thanks for this very useful driver. It will surely save us a lot of development work.

**Comment by urrsk** [comment]
@SharxRobotics Thanks for asking.
Good suggestion, I will get this prioritized.
Though you are also welcome to make them your self. The [URDF files are heavy inspired from the ones used for the ROS Driver](https://github.com/ros-industrial/universal_robot/tree/kinetic-devel/ur_e_description/urdf) and the DH parameter can be found on [Universal Robots support page](https://www.universal-robots.com/articles/ur/application-installation/dh-parameters-for-calculations-of-kinematics-and-dynamics/)

It is safe to run it with the wrong kinematics model as dynamics are controlled by the robot controller. Though the forward and inverse kinematics done in Isaac will be wrong.

**Comment by SharxRobotics** [comment]
Thanks so much for your reply. 

Yes having your official files supporting UR3e and UR5e would be nice. 

Also thanks for confirming the safety of temporarily using the UR10 files, even if the kinematics aren't correct. We now have your Isaac driver working and communicating with your simulator and can see that the "shufflebox" example goes nicely through the motions to the different waypoints. It is not causing any faults or collisions unless it is deliberately started in an initial position that is near collision. Even then the simulator catches the fault and shuts down the robot, so presumably that would happen with the real arm as well.

So far it seems to work in Isaac 2021 too. We should be getting a UR3e soon and will report back once we've controlled the real arm through Isaac, not just the simulator.  Perhaps we'll post a video to the UR forum showcase section as well.

**Comment by urrsk** [comment]
@SharxRobotics Sounds good, you are welcome to post on the UR forum.
You can also reach out to me though the ROS@universal-robots.com

I will be happy to receive feedback, good and bad.

**Comment by urmahp** [comment]
I have added a PR #7, which includes kinematic models for all the robot models. @SharxRobotics you are more than welcome to try out #7 and tell us how it worked out. 

The URDF files hasn't been added yet, only the kinematic JSON files. However, the kinematic files should be enough to do forward and inverse kinematic calculations in Isaac.

**Comment by SharxRobotics** [comment]
That’s wonderful, thanks for sharing, we will definitely try this and will report back.

Meanwhile we got the UR3e working with Isaac, including the real robot arm, and your URsim simulator, and Nvidia’s Omniverse simulator.  

Not sure if this picture can be viewed in Github but in any event we will post a lot of pictures and videos on our Sharx Robotics dot com web site early next year.

![image](https://user-images.githubusercontent.com/94851393/147531868-18505712-b3b6-4f4d-8a24-4dc4556a915d.png)

Cheers!

**Comment by urrsk** [comment]
@SharxRobotics any updates?
